### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by leilakhalili87** [leilakhalili87/gbmc_v0#2]
- [x] pad_dump_file --> all non-fcc atoms are considered as defects
- [x] lammps_input -->  1 func for min and 1 func for rest

- [x] lammps_input --> only min has rigid_fix

- [ ] fix test cases

- [ ] add explanation for the test cases

- [ ] find the cc-coordinates from insertion_move.py and scale it

- [ ] build a prob distribution

- [ ] generate random number, smaller than 1/2 removal

- [ ] just run the codes needed, if removal no need to find the cc_ccor?

- [ ] remove atom from dump file--> check whether you can still have the same atom ID

- [ ] perform min

- [ ] find GB energy after min 

- [ ] calculate \delta E_GB

- [ ] new E< old E accept the new struct

- [ ] new E < old E find boltzman prob 

- [ ] create new random num --> if smaller than B prob accept else reject

- [ ] find the case GB region is very close to surface

- [ ] change lammps_box and next func, to be able to handle diff periodicity
